spring:
  application:
    name: simple-service-with-discovery
    
server:
  port: ${port:8989}

eureka:
  instance:
    appname: simple-service-with-discovery-testapp
    hostname: ${vcap.application.uris[0]:localhost}
    non-secure-port: ${server.port}
    non-secure-port-enabled: false
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}-${eureka.instance.metadata-map.uuid}}
      uuid: ${random.uuid}
    lease-expiration-duration-in-seconds: 5 
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:${server.port}
    